name: TGS_env_2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - debreak=1.3
  - numpy=1.21.6
  - pip=24.0
  - pysam=0.19.0
  - python=3.7.8
  - pytorch=1.10.1
  - pillow==9.2.0
  - scipy==1.7.3
  - pip:
    - opencv-python==4.10.0.84
