name: NGS_env_1
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.17
  - bedtools=2.31.1
  - bioconductor-cn.mops
  - bwa=0.7.18
  - cnvpytor=1.3.1
  - delly=0.7.6
  - fastp=0.23.4
  - gatk=3.8
  - gridss=2.13.2
  - pip=24.0
  - python=3.11.0
  - r-exomedepth=1.1.16
  - sambamba=1.0
  - samtools=1.18
  - survivor=1.0.7
  - vcftools=0.1.16
  - xhmm=0.0.0.2016_01_04.cc14e52
  - wham=1.8.0.1.2017.05.03
  - pip:
      - click==8.1.7
      - pandas==2.2.2
      - scikit-learn==1.5.1
      